
define( [
    'SCENERY/CanvasLayer',
    'SCENERY/Color',
    'SCENERY/DebugContext',
    'SCENERY/DOM',
    'SCENERY/DOMLayer',
    'SCENERY/Event',
    'SCENERY/Fillable',
    'SCENERY/Finger',
    'SCENERY/Font',
    'SCENERY/Image',
    'SCENERY/Input',
    'SCENERY/Key',
    'SCENERY/Layer',
    'SCENERY/LayerState',
    'SCENERY/LayerStrategy',
    'SCENERY/LayerType',
    'SCENERY/Mouse',
    'SCENERY/Node',
    'SCENERY/Path',
    'SCENERY/RenderState',
    'SCENERY/Scene',
    'SCENERY/Shape',
    'SCENERY/SimpleDragHandler',
    'SCENERY/Strokable',
    'SCENERY/SVGLayer',
    'SCENERY/Text',
    'SCENERY/Touch',
    'SCENERY/Trail',
    'SCENERY/TrailPointer',
    'SCENERY/Util',
    'SCENERY/scenery'
  ], function(
    CanvasLayer,
    Color,
    DebugContext,
    DOM,
    DOMLayer,
    Event,
    Fillable,
    Finger,
    Font,
    Image,
    Input,
    Key,
    Layer,
    LayerState,
    LayerStrategy,
    LayerType,
    Mouse,
    Node,
    Path,
    RenderState,
    Scene,
    Shape,
    SimpleDragHandler,
    Strokable,
    SVGLayer,
    Text,
    Touch,
    Trail,
    TrailPointer,
    Util,
    scenery
  ) {
  
  return scenery;
} );
