(function() {
  'use strict';

  module( 'Scenery: Fuzzer Excerpts' );

  test( 'Instance.addRemoveCounter === -2 failure (#392)', function() {
    var scene = new scenery.Node();
    var display = new scenery.Display( scene );
    display.updateDisplay();
    var node0 = new scenery.Node();
    var node1 = new scenery.Node();
    var node2 = new scenery.Node();
    var node3 = new scenery.Node();
    var node4 = new scenery.Node();
    var node5 = new scenery.Node();
    var node6 = new scenery.Node();
    var path0 = new scenery.Path();
    var path1 = new scenery.Path();
    var path2 = new scenery.Path();
    var path3 = new scenery.Path();
    var text0 = new scenery.Text( '0!' );
    var text1 = new scenery.Text( '1!' );
    var text2 = new scenery.Text( '2!' );
    node2.insertChild( 0, node0 );
    display.updateDisplay();
    path3.insertChild( 0, node3 );
    path3.removeChild( node3 );
    display.updateDisplay();
    node4.insertChild( 0, node1 );
    path3.insertChild( 0, node4 );
    node2.insertChild( 1, path3 );
    scene.insertChild( 0, path1 );
    node2.insertChild( 1, path1 );
    node4.removeChild( node1 );
    node6.insertChild( 0, scene );
    scene.removeChild( path1 );
    path0.insertChild( 0, node2 );
    path0.insertChild( 0, node6 );
    display.updateDisplay();
    path0.insertChild( 1, path3 );
    node6.removeChild( scene );
    display.updateDisplay();
    display.updateDisplay();
    display.updateDisplay();
    path1.insertChild( 0, node0 );
    display.updateDisplay();
    node4.insertChild( 0, path2 );
    path3.removeChild( node4 );
    display.updateDisplay();
    display.updateDisplay();
    node5.insertChild( 0, node0 );
    node4.insertChild( 0, node5 );
    display.updateDisplay();
    node4.removeChild( path2 );
    display.updateDisplay();
    node4.removeChild( node5 );
    scene.insertChild( 0, node4 );
    scene.removeChild( node4 );
    node3.insertChild( 0, node2 );
    node3.insertChild( 0, path0 );
    path1.removeChild( node0 );
    display.updateDisplay();
    path3.insertChild( 0, node5 );
    display.updateDisplay();
    node2.removeChild( node0 );
    display.updateDisplay();
    display.updateDisplay();
    display.updateDisplay();
    path3.removeChild( node5 );
    display.updateDisplay();
    display.updateDisplay();
    path2.insertChild( 0, path3 );
    node1.insertChild( 0, node2 );
    path3.insertChild( 0, node6 );
    display.updateDisplay();
    path2.insertChild( 0, path1 );
    path2.removeChild( path1 );
    path3.removeChild( node6 );
    scene.insertChild( 0, node4 );
    display.updateDisplay();
    node6.insertChild( 0, node5 );
    scene.removeChild( node4 );
    node4.insertChild( 0, path2 );
    display.updateDisplay();
    node6.removeChild( node5 );
    display.updateDisplay();
    node5.removeChild( node0 );
    path0.removeChild( path3 );
    display.updateDisplay();
    path2.insertChild( 1, path0 );
    display.updateDisplay();
    display.updateDisplay();
    path0.removeChild( node6 );
    path0.removeChild( node2 );
    node1.insertChild( 1, path3 );
    node3.insertChild( 1, node1 );
    display.updateDisplay();
    node4.removeChild( path2 );
    display.updateDisplay();
    path0.insertChild( 0, scene );
    display.updateDisplay();
    node6.insertChild( 0, node2 );
    node5.insertChild( 0, path0 );
    node4.insertChild( 0, node6 );
    node0.insertChild( 0, node4 );
    node0.removeChild( node4 );
    display.updateDisplay();
    node6.removeChild( node2 );
    path2.removeChild( path3 );
    path2.insertChild( 0, path3 );
    node2.insertChild( 1, node6 );
    display.updateDisplay();
    path0.removeChild( scene );
    node2.removeChild( node6 );
    node6.insertChild( 0, path0 );
    display.updateDisplay();
    path2.insertChild( 0, node3 );
    path1.insertChild( 0, node6 );
    node1.removeChild( path3 );
    display.updateDisplay();
    path1.insertChild( 0, node4 );
    path2.insertChild( 1, node1 );
    node5.removeChild( path0 );
    display.updateDisplay();
    display.updateDisplay();
    node2.removeChild( path3 );
    display.updateDisplay();
    display.updateDisplay();
    display.updateDisplay();
    path0.insertChild( 0, node0 );
    node4.removeChild( node6 );
    display.updateDisplay();
    display.updateDisplay();
    node2.insertChild( 0, node5 );
    path2.insertChild( 3, scene );
    display.updateDisplay();
    path3.insertChild( 0, scene );
    display.updateDisplay();
    path1.insertChild( 2, scene );
    path1.removeChild( node6 );
    node1.insertChild( 0, path1 );
    node2.removeChild( node5 );
    path3.insertChild( 1, node5 );
    node0.insertChild( 0, node4 );
    path0.removeChild( node0 );
    node3.removeChild( path0 );
    node0.insertChild( 1, node3 );
    node1.insertChild( 0, path3 );
    path1.removeChild( node4 );
    node3.insertChild( 2, node5 );
    path2.removeChild( node3 );
    node4.insertChild( 0, path1 );
    node5.insertChild( 0, node4 );
    node3.removeChild( node2 );
    path3.removeChild( scene );
    node3.insertChild( 0, node6 );
    node2.insertChild( 1, node5 );
    path0.insertChild( 0, path1 );
    path2.insertChild( 3, node3 );
    node2.removeChild( path1 );
    display.updateDisplay();
    path0.removeChild( path1 );
    node5.removeChild( node4 );
    node4.insertChild( 0, path0 );
    node4.removeChild( path0 );
    node6.removeChild( path0 );
    node1.removeChild( path3 );
    display.updateDisplay();
    node3.removeChild( node6 );
    display.updateDisplay();
    node4.removeChild( path1 );
    node5.insertChild( 0, path0 );
    path3.insertChild( 1, node4 );
    node0.insertChild( 0, path2 );
    path2.removeChild( path3 );
    node5.removeChild( path0 );
    node0.insertChild( 2, path0 );
    node3.removeChild( node1 );
    node2.insertChild( 0, node4 );
    path3.removeChild( node5 );
    path1.removeChild( scene );
    display.updateDisplay();
    display.updateDisplay();
    display.updateDisplay();
    node1.removeChild( path1 );
    node5.insertChild( 0, node6 );
    scene.insertChild( 0, path0 );
    node1.removeChild( node2 );
    path3.removeChild( node4 );
    display.updateDisplay();
    node2.removeChild( node4 );
    node0.removeChild( path2 );
    display.updateDisplay();
    display.updateDisplay();
    path2.insertChild( 1, path3 );
    node3.insertChild( 0, node2 );
    node2.insertChild( 0, path3 );
    node2.removeChild( path3 );
    node3.removeChild( node2 );
    node2.insertChild( 0, node1 );
    path2.removeChild( scene );
    node2.removeChild( node5 );
    scene.removeChild( path0 );
    path1.insertChild( 0, node4 );
    node0.removeChild( path0 );
    node3.insertChild( 0, path1 );
    node5.insertChild( 0, scene );
    node5.removeChild( scene );
    display.updateDisplay();
    node2.insertChild( 1, node0 );
    path3.insertChild( 0, node0 );
    display.updateDisplay();
    node0.insertChild( 2, node1 );
    path2.removeChild( path3 );
    path1.removeChild( node4 );
    node3.removeChild( node5 );
    node6.insertChild( 0, node1 );
    node2.insertChild( 1, path2 );
    path3.removeChild( node0 );
    node2.insertChild( 2, node5 );
    node5.insertChild( 0, path0 );
    display.updateDisplay();
    node2.insertChild( 1, node3 );
    display.updateDisplay();
    node3.insertChild( 0, path0 );
    node3.insertChild( 0, node1 );
    display.updateDisplay();
    path3.insertChild( 0, node5 );
    node5.insertChild( 2, node3 );
    node3.insertChild( 3, node6 );
    node2.removeChild( node5 );
    path1.insertChild( 0, node4 );
    path0.insertChild( 0, node6 );
    node0.removeChild( node1 );
    path1.removeChild( node4 );
    path0.insertChild( 1, node1 );
    node3.removeChild( node6 );
    path2.insertChild( 1, path3 );
    path2.removeChild( node3 );
    path2.removeChild( path0 );
    path2.removeChild( path3 );
    display.updateDisplay();
    path2.removeChild( node1 );
    node3.removeChild( path1 );
    node2.removeChild( node1 );
    node3.removeChild( path0 );
    path1.insertChild( 0, scene );
    node4.insertChild( 0, node6 );
    node5.removeChild( node6 );
    node6.removeChild( node1 );
    node2.insertChild( 3, path0 );
    path1.removeChild( scene );
    node4.removeChild( node6 );
    node6.insertChild( 0, path1 );
    node5.removeChild( path0 );
    node0.insertChild( 1, node6 );
    node5.removeChild( node3 );
    node4.insertChild( 0, node6 );
    path3.removeChild( node5 );
    path0.removeChild( node1 );
    display.updateDisplay();
    path2.insertChild( 0, node6 );
    display.updateDisplay();
    scene.insertChild( 0, path1 );
    scene.insertChild( 1, node1 );
    node6.removeChild( path1 );
    path0.insertChild( 0, node3 );
    node4.removeChild( node6 );
    path1.insertChild( 0, node3 );
    path0.insertChild( 2, path1 );
    path2.insertChild( 1, scene );
    display.updateDisplay();
    path1.removeChild( node3 );
    node3.removeChild( node1 );
    display.updateDisplay();
    display.updateDisplay();
    path3.insertChild( 0, node5 );
    path3.removeChild( node5 );
    path0.removeChild( node3 );
    node5.insertChild( 0, path0 );
    path0.insertChild( 1, path2 );
    node0.insertChild( 2, path2 );
    display.updateDisplay();
    node1.insertChild( 0, node3 );
    path3.insertChild( 0, node5 );
    node2.removeChild( node0 );
    display.updateDisplay();
    node4.insertChild( 0, scene );
    node2.removeChild( path0 );
    node0.removeChild( path2 );
    scene.insertChild( 0, node6 );
    display.updateDisplay();
    node2.insertChild( 0, node0 );
    display.updateDisplay();
    node2.insertChild( 2, scene );
    node2.insertChild( 2, node1 );
    path3.insertChild( 0, path1 );
    path2.removeChild( scene );
    path2.removeChild( node6 );
    node4.removeChild( scene );
    display.updateDisplay();
    path3.removeChild( node5 );
    node4.insertChild( 0, path1 );
    display.updateDisplay();
    path3.insertChild( 1, node5 );
    node4.removeChild( path1 );
    scene.insertChild( 2, path0 );
    node0.insertChild( 2, path2 );
    path0.removeChild( path2 );
    scene.insertChild( 2, node5 );
    node5.removeChild( path0 );
    path3.insertChild( 2, node0 );
    node0.removeChild( node6 );
    display.updateDisplay();
    node0.removeChild( node3 );
    display.updateDisplay();
    display.updateDisplay();
    scene.insertChild( 5, path2 );
    display.updateDisplay();
    display.updateDisplay();
    node6.insertChild( 0, path1 );
    node6.removeChild( path1 );
    node5.insertChild( 0, node3 );
    display.updateDisplay();
    node6.insertChild( 0, node4 );
    node6.removeChild( node4 );
    path3.removeChild( path1 );
    node5.removeChild( node3 );
    path3.insertChild( 0, path2 );
    path1.insertChild( 0, node1 );
    node0.removeChild( node4 );
    node0.insertChild( 0, node4 );
    node1.removeChild( node3 );
    path1.removeChild( node1 );
    node0.insertChild( 1, path0 );
    node4.insertChild( 0, path2 );
    node3.insertChild( 0, path1 );
    display.updateDisplay();
    node0.removeChild( node4 );
    display.updateDisplay();
    path1.insertChild( 0, node1 );
    display.updateDisplay();
    node3.removeChild( path1 );
    node3.insertChild( 0, path0 );
    display.updateDisplay();
    node5.insertChild( 0, node0 );
    display.updateDisplay();
    display.updateDisplay();
    display.updateDisplay();
    node4.insertChild( 1, node0 );
    path1.removeChild( node1 );
    path0.removeChild( path1 );
    node2.insertChild( 3, path3 );
    path3.insertChild( 0, node6 );
    path3.insertChild( 3, node4 );
    display.updateDisplay();
    node5.removeChild( node0 );
    display.updateDisplay();
    node3.insertChild( 1, path1 );
    path0.insertChild( 1, path1 );
    display.updateDisplay();
    node0.insertChild( 2, node1 );
    node3.insertChild( 0, node6 );
    scene.removeChild( path2 );
    scene.removeChild( node6 );
    node4.removeChild( node0 );
    node3.removeChild( node6 );
    node5.insertChild( 0, node1 );
    node1.insertChild( 0, path2 );
    display.updateDisplay();
    display.updateDisplay();
    display.updateDisplay();
    path3.insertChild( 2, node1 );
    display.updateDisplay();
    display.updateDisplay();
    display.updateDisplay();
    scene.removeChild( path0 );
    display.updateDisplay();
    display.updateDisplay();
    path3.removeChild( node0 );
    node6.insertChild( 0, path2 );
    node6.insertChild( 1, node4 );
    node2.removeChild( scene );
    node4.removeChild( path2 );
    scene.removeChild( node5 );
    display.updateDisplay();
    path3.insertChild( 3, path1 );
    display.updateDisplay();
    node2.insertChild( 0, node6 );
    node2.removeChild( node0 );
    node1.removeChild( path2 );
    node2.removeChild( path2 );
    node2.removeChild( node3 );
    display.updateDisplay();
    display.updateDisplay();
    scene.insertChild( 2, node2 );
    path1.insertChild( 0, node5 );
    display.updateDisplay();
    node2.removeChild( node6 );
    display.updateDisplay();
    scene.removeChild( path1 );
    node3.removeChild( path0 );
    node0.removeChild( path2 );
    scene.insertChild( 0, path0 );
    path2.insertChild( 0, node4 );
    scene.insertChild( 3, node0 );
    node2.removeChild( path3 );
    scene.removeChild( path0 );
    path2.removeChild( node4 );
    path1.removeChild( node5 );
    display.updateDisplay();
    scene.insertChild( 2, node3 );
    path1.insertChild( 0, node6 );
    node6.removeChild( node4 );
    node4.insertChild( 0, node0 );
    node3.removeChild( path1 );
    display.updateDisplay();
    display.updateDisplay();
    display.updateDisplay();
    node2.insertChild( 1, path0 );
    display.updateDisplay();
    display.updateDisplay();
    node2.removeChild( node1 );
    node4.insertChild( 0, scene );
    node4.insertChild( 2, path2 );
    display.updateDisplay();
    display.updateDisplay();
    node2.insertChild( 0, node1 );
    display.updateDisplay();
    display.updateDisplay();
    path3.insertChild( 0, scene );
    display.updateDisplay();
    node0.removeChild( node1 );
    node0.removeChild( path0 );
    display.updateDisplay();
    node6.removeChild( path2 );
    path2.insertChild( 0, path0 );
    node2.insertChild( 0, node0 );
    node1.insertChild( 0, path0 );
    node1.removeChild( path0 );
    scene.removeChild( node2 );
    node1.insertChild( 0, path0 );
    node5.removeChild( node1 );
    path1.removeChild( node6 );
    path0.removeChild( path1 );
    path3.removeChild( path2 );
    node3.insertChild( 0, node2 );
    display.updateDisplay();
    node3.insertChild( 0, node6 );
    display.updateDisplay();
    path3.removeChild( path1 );
    display.updateDisplay();
    node4.removeChild( scene );
    display.updateDisplay();
    path3.removeChild( scene );
    node0.insertChild( 0, node6 );
    scene.removeChild( node3 );
    path3.insertChild( 1, node3 );
    path2.removeChild( path0 );
    path2.insertChild( 0, path0 );
    path3.removeChild( node1 );
    path1.insertChild( 0, node2 );
    display.updateDisplay();
    node0.insertChild( 1, node5 );
    display.updateDisplay();
    scene.insertChild( 2, node3 );
    display.updateDisplay();
    node4.removeChild( node0 );
    node2.insertChild( 2, node4 );
    node1.removeChild( path0 );
    node1.insertChild( 0, node6 );
    scene.insertChild( 1, path0 );
    path0.removeChild( node6 );
    display.updateDisplay();
    node1.removeChild( node6 );
    display.updateDisplay();
    node1.insertChild( 0, path0 );
    display.updateDisplay();
    display.updateDisplay();
    path2.removeChild( path0 );
    node3.insertChild( 0, node0 );
    node2.removeChild( node4 );
    node3.insertChild( 3, path0 );
    node1.removeChild( path0 );
    path1.insertChild( 0, node5 );
    node2.removeChild( node0 );
    path2.insertChild( 0, node1 );
    display.updateDisplay();
    scene.removeChild( node1 );
    node0.removeChild( node5 );
    node4.removeChild( path2 );
    node0.removeChild( node6 );

    expect( 0 );
  } );

})();
