// Copyright 2023, University of Colorado Boulder

/**
 * IMPORTANT: AUTOGENERATED from generate.js. DO NOT MODIFY DIRECTLY
 *
 * wasm_bindgen generated bindings for Guillotiere
 */

// Disable linting for the entire file
/* eslint-disable */
let wasm;

const cachedTextDecoder = (typeof TextDecoder !== 'undefined' ? new TextDecoder('utf-8', { ignoreBOM: true, fatal: true }) : { decode: () => { throw Error('TextDecoder not available') } } );

if (typeof TextDecoder !== 'undefined') { cachedTextDecoder.decode(); };

let cachedUint8Memory0 = null;

function getUint8Memory0() {
    if (cachedUint8Memory0 === null || cachedUint8Memory0.byteLength === 0) {
        cachedUint8Memory0 = new Uint8Array(wasm.memory.buffer);
    }
    return cachedUint8Memory0;
}

function getStringFromWasm0(ptr, len) {
    ptr = ptr >>> 0;
    return cachedTextDecoder.decode(getUint8Memory0().subarray(ptr, ptr + len));
}

let cachedInt32Memory0 = null;

function getInt32Memory0() {
    if (cachedInt32Memory0 === null || cachedInt32Memory0.byteLength === 0) {
        cachedInt32Memory0 = new Int32Array(wasm.memory.buffer);
    }
    return cachedInt32Memory0;
}
/**
*/
export function run() {
    wasm.run();
}

/**
*/
export class GuillotiereAtlas {

    static __wrap(ptr) {
        ptr = ptr >>> 0;
        const obj = Object.create(GuillotiereAtlas.prototype);
        obj.__wbg_ptr = ptr;

        return obj;
    }

    __destroy_into_raw() {
        const ptr = this.__wbg_ptr;
        this.__wbg_ptr = 0;

        return ptr;
    }

    free() {
        const ptr = this.__destroy_into_raw();
        wasm.__wbg_guillotiereatlas_free(ptr);
    }
    /**
    * @param {number} width
    * @param {number} height
    */
    constructor(width, height) {
        const ret = wasm.guillotiereatlas_new(width, height);
        return GuillotiereAtlas.__wrap(ret);
    }
    /**
    * @param {number} width
    * @param {number} height
    * @returns {GuillotiereBin}
    */
    allocate(width, height) {
        const ret = wasm.guillotiereatlas_allocate(this.__wbg_ptr, width, height);
        return GuillotiereBin.__wrap(ret);
    }
    /**
    * @param {number} id
    */
    deallocate(id) {
        wasm.guillotiereatlas_deallocate(this.__wbg_ptr, id);
    }
    /**
    * @returns {boolean}
    */
    is_empty() {
        const ret = wasm.guillotiereatlas_is_empty(this.__wbg_ptr);
        return ret !== 0;
    }
    /**
    */
    clear() {
        wasm.guillotiereatlas_clear(this.__wbg_ptr);
    }
    /**
    * @returns {string}
    */
    rearrange() {
        let deferred1_0;
        let deferred1_1;
        try {
            const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
            wasm.guillotiereatlas_rearrange(retptr, this.__wbg_ptr);
            var r0 = getInt32Memory0()[retptr / 4 + 0];
            var r1 = getInt32Memory0()[retptr / 4 + 1];
            deferred1_0 = r0;
            deferred1_1 = r1;
            return getStringFromWasm0(r0, r1);
        } finally {
            wasm.__wbindgen_add_to_stack_pointer(16);
            wasm.__wbindgen_free(deferred1_0, deferred1_1, 1);
        }
    }
    /**
    * @param {number} width
    * @param {number} height
    * @returns {string}
    */
    resize_and_rearrange(width, height) {
        let deferred1_0;
        let deferred1_1;
        try {
            const retptr = wasm.__wbindgen_add_to_stack_pointer(-16);
            wasm.guillotiereatlas_resize_and_rearrange(retptr, this.__wbg_ptr, width, height);
            var r0 = getInt32Memory0()[retptr / 4 + 0];
            var r1 = getInt32Memory0()[retptr / 4 + 1];
            deferred1_0 = r0;
            deferred1_1 = r1;
            return getStringFromWasm0(r0, r1);
        } finally {
            wasm.__wbindgen_add_to_stack_pointer(16);
            wasm.__wbindgen_free(deferred1_0, deferred1_1, 1);
        }
    }
    /**
    * @param {number} width
    * @param {number} height
    */
    grow(width, height) {
        wasm.guillotiereatlas_grow(this.__wbg_ptr, width, height);
    }
}
/**
*/
export class GuillotiereBin {

    static __wrap(ptr) {
        ptr = ptr >>> 0;
        const obj = Object.create(GuillotiereBin.prototype);
        obj.__wbg_ptr = ptr;

        return obj;
    }

    __destroy_into_raw() {
        const ptr = this.__wbg_ptr;
        this.__wbg_ptr = 0;

        return ptr;
    }

    free() {
        const ptr = this.__destroy_into_raw();
        wasm.__wbg_guillotierebin_free(ptr);
    }
    /**
    * @returns {boolean}
    */
    is_valid() {
        const ret = wasm.guillotierebin_is_valid(this.__wbg_ptr);
        return ret !== 0;
    }
    /**
    * @returns {number}
    */
    get id() {
        const ret = wasm.guillotierebin_get_id(this.__wbg_ptr);
        return ret >>> 0;
    }
    /**
    * @returns {number}
    */
    get x() {
        const ret = wasm.guillotierebin_get_x(this.__wbg_ptr);
        return ret;
    }
    /**
    * @returns {number}
    */
    get y() {
        const ret = wasm.guillotierebin_get_y(this.__wbg_ptr);
        return ret;
    }
}

async function __wbg_load(module, imports) {
    if (typeof Response === 'function' && module instanceof Response) {
        if (typeof WebAssembly.instantiateStreaming === 'function') {
            try {
                return await WebAssembly.instantiateStreaming(module, imports);

            } catch (e) {
                if (module.headers.get('Content-Type') != 'application/wasm') {
                    console.warn("`WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:\n", e);

                } else {
                    throw e;
                }
            }
        }

        const bytes = await module.arrayBuffer();
        return await WebAssembly.instantiate(bytes, imports);

    } else {
        const instance = await WebAssembly.instantiate(module, imports);

        if (instance instanceof WebAssembly.Instance) {
            return { instance, module };

        } else {
            return instance;
        }
    }
}

function __wbg_get_imports() {
    const imports = {};
    imports.wbg = {};
    imports.wbg.__wbindgen_throw = function(arg0, arg1) {
        throw new Error(getStringFromWasm0(arg0, arg1));
    };

    return imports;
}

function __wbg_init_memory(imports, maybe_memory) {

}

function __wbg_finalize_init(instance, module) {
    wasm = instance.exports;
    __wbg_init.__wbindgen_wasm_module = module;
    cachedInt32Memory0 = null;
    cachedUint8Memory0 = null;

    wasm.__wbindgen_start();
    return wasm;
}

function initSync(module) {
    if (wasm !== undefined) return wasm;

    const imports = __wbg_get_imports();

    __wbg_init_memory(imports);

    if (!(module instanceof WebAssembly.Module)) {
        module = new WebAssembly.Module(module);
    }

    const instance = new WebAssembly.Instance(module, imports);

    return __wbg_finalize_init(instance, module);
}

async function __wbg_init(input) {
    if (wasm !== undefined) return wasm;

    const imports = __wbg_get_imports();

    __wbg_init_memory(imports);

    const { instance, module } = await __wbg_load(input, imports);

    return __wbg_finalize_init(instance, module);
}

export { initSync }
export default __wbg_init;
