/* eslint-disable */
import bump from './shared/bump.js';
import bbox from './shared/bbox.js';
import drawtag from './shared/drawtag.js';
import config from './shared/config.js';

export default `${config}
${drawtag}
${bbox}
${bump}
@group(0)@binding(0)var<uniform>f:aF;@group(0)@binding(1)var<storage>bS:array<aE>;@group(0)@binding(2)var<storage>h2:array<cY>;@group(0)@binding(3)var<storage>h1:array<vec4f>;@group(0)@binding(4)var<storage,read_write>h0:array<vec4f>;@group(0)@binding(5)var<storage,read_write>ad:eh;@group(0)@binding(6)var<storage,read_write>h_:array<u32>;struct e6{bc:u32,b5:u32}@group(0)@binding(7)var<storage,read_write>dt:array<e6>;const ap=.00390625;const bd=.00390625;const h=256u;const b6=8u;const go=4u;var<workgroup>bs:array<array<atomic<u32>,aB>,b6>;var<workgroup>gi:array<array<u32,aB>,go>;var<workgroup>gh:array<u32,aB>;@compute @workgroup_size(256)fn main(@builtin(global_invocation_id)E:vec3u,@builtin(local_invocation_id)d:vec3u,@builtin(workgroup_id)ae:vec3u,){for(var c=0u;c<b6;c+=1u){atomicStore(&bs[c][d.x],0u);}workgroupBarrier();let d_=E.x;var B=0;var I=0;var J=0;var M=0;if d_<f.cA{let dv=bS[d_];var gk=vec4(-1e9,-1e9,1e9,1e9);if dv.b8>0u{gk=h1[min(dv.b8- 1u,f.ed- 1u)];}let aI=h2[dv.R];let h7=vec4f(vec4(aI.B,aI.I,aI.J,aI.M));let e=dG(gk,h7);h0[d_]=e;if e.x<e.z&&e.y<e.w{B=i32(floor(e.x*ap));I=i32(floor(e.y*bd));J=i32(ceil(e.z*ap));M=i32(ceil(e.w*bd));}}let cM=i32((f.aA+a1- 1u)/a1);let gn=i32((f.cB+cC- 1u)/cC);B=clamp(B,0,cM);I=clamp(I,0,gn);J=clamp(J,0,cM);M=clamp(M,0,gn);if B==J{M=I;}var x=B;var y=I;let dZ=d.x/32u;let e5=1u<<(d.x&31u);while y<M{atomicOr(&bs[dZ][y*cM+x],e5);x+=1;if x==J{x=B;y+=1;}}workgroupBarrier();var bc=0u;for(var c=0u;c<go;c+=1u){bc+=countOneBits(atomicLoad(&bs[c*2u][d.x]));let h6=bc;bc+=countOneBits(atomicLoad(&bs[c*2u+1u][d.x]));let h5=bc;let h4=h6|(h5<<16u);gi[c][d.x]=h4;}var b5=atomicAdd(&ad.fk,bc);if b5+bc>f.il{b5=0u;atomicOr(&ad.af,eg);}gh[d.x]=b5;dt[E.x].bc=bc;dt[E.x].b5=b5;workgroupBarrier();x=B;y=I;while y<M{let du=y*cM+x;let gm=atomicLoad(&bs[dZ][du]);if(gm&e5)!=0u{var gj=countOneBits(gm&(e5- 1u));if dZ>0u{let gl=dZ- 1u;let h3=gi[gl/2u][du];gj+=(h3>>(16u*(gl&1u)))&0xffffu;}let aR=f.gQ+gh[du];h_[aR+gj]=d_;}x+=1;if x==J{x=B;y+=1;}}}`
