/* eslint-disable */
import drawtag from './shared/drawtag.js';
import clip from './shared/clip.js';
import bbox from './shared/bbox.js';
import config from './shared/config.js';
import pre from './shared/pre.js';

export default `${pre}${config}
${bbox}
${clip}
${drawtag}
@group(0)@binding(0)var<uniform>n:aR;@group(0)@binding(1)var<storage>cX:array<eu>;@group(0)@binding(2)var<storage>bR:array<da>;@group(0)@binding(3)var<storage>aP:array<a3>;@group(0)@binding(4)var<storage>ib:array<fz>;@group(0)@binding(5)var<storage,read_write>b7:array<aQ>;@group(0)@binding(6)var<storage,read_write>ia:array<af>;const o=256u;var<workgroup>aO:array<a3,510>;var<workgroup>gq:array<i,o>;var<workgroup>dG:array<af,o>;var<workgroup>eb:array<af,o>;var<workgroup>ea:array<m,o>;fn ie(am:ptr<function,a3>,h9:i)->m{var p=h9;var bE=e;while bE<firstTrailingBit(o){let an=2u*o-(2u<<(firstTrailingBit(o)-bE));if((p>>bE)&f)!=e{let dH=dU(aO[an+(p>>bE)-f],*am);if dH.b>e{break;}*am=dH;p-=f<<bE;}bE+=f;}if p>e{while bE>e{bE-=f;let an=2u*o-(2u<<(firstTrailingBit(o)-bE));let dH=dU(aO[an+(p>>bE)- f],*am);if dH.b==e{*am=dH;p-=f<<bE;}}}if p>e{return m(p)- 1;}else{return m(~e-(*am).a);}}fn ic(p:i)->m{if p<n.es{return cX[p].ac;}else{return-2147483648;}}@compute @workgroup_size(256)fn main(@builtin(global_invocation_id)N:M,@builtin(local_invocation_id)k:M,@builtin(workgroup_id)at:M){var am:a3;if k.x<at.x{am=aP[k.x];}aO[k.x]=am;for(var j=e;j<firstTrailingBit(o);j+=f){workgroupBarrier();if k.x+(f<<j)<o{let aw=aO[k.x+(f<<j)];am=dU(am,aw);}workgroupBarrier();aO[k.x]=am;}workgroupBarrier();let fj=aO[0].b;let fi=o- f-k.x;var p=e;for(var j=e;j<firstTrailingBit(o);j+=f){let bG=p+((o/2u)>>j);if fi<aO[bG].b{p=bG;}}let b=aO[p].b;var l=vec4(-1e9,-1e9,1e9,1e9);if fi<b{let gw=ib[p*o+b-fi- f];gq[k.x]=gw.dT;l=gw.l;}for(var j=e;j<firstTrailingBit(o);j+=f){dG[k.x]=l;workgroupBarrier();if k.x>=(f<<j){l=dV(dG[k.x-(f<<j)],l);}workgroupBarrier();}dG[k.x]=l;let cY=ic(N.x);let cj=cY>=0;am=a3(f-i(cj),i(cj));aO[k.x]=am;if cj{let aU=bR[cY];l=vec4(h(aU.J),h(aU.R),h(aU.T),h(aU.V));}else{l=vec4(-1e9,-1e9,1e9,1e9);}var gs=e;for(var j=e;j<firstTrailingBit(o)- f;j+=f){let gv=2u*o-(f<<(firstTrailingBit(o)-j));workgroupBarrier();if k.x<f<<(firstTrailingBit(o)- f-j){let gu=gs+k.x*2u;aO[gv+k.x]=dU(aO[gu],aO[gu+f]);}gs=gv;}workgroupBarrier();am=a3();var aT=ie(&am,k.x);ea[k.x]=aT;workgroupBarrier();let ec=select(aT- 1,ea[aT],aT>=0);var dF:m;if aT>=0{dF=m(at.x*o)+aT;}else if aT+m(fj)>=0{dF=m(gq[m(o)+aT]);}else{dF=-1;}for(var j=e;j<firstTrailingBit(o);j+=f){if j!=e{ea[k.x]=aT;}eb[k.x]=l;workgroupBarrier();if aT>=0{l=dV(eb[aT],l);aT=ea[aT];}workgroupBarrier();}if aT+m(fj)>=0{l=dV(dG[m(o)+aT],l);}eb[k.x]=l;workgroupBarrier();if!cj&&N.x<n.es{let gt=cX[dF];let ac=gt.ac;let dT=gt.p;let p=~cY;b7[p].ac=i(ac);b7[p].bM=b7[dT].bM;if ec>=0{l=eb[ec];}else if ec+m(fj)>=0{l=dG[m(o)+ec];}else{l=vec4(-1e9,-1e9,1e9,1e9);}}if N.x<n.es{ia[N.x]=l;}}`
