/* eslint-disable */
import drawtag from './shared/drawtag.js';
import clip from './shared/clip.js';
import bbox from './shared/bbox.js';
import config from './shared/config.js';
import pre from './shared/pre.js';

export default `${pre}${config}
${bbox}
${clip}
${drawtag}
@group(0)@binding(0)var<uniform>n:aR;@group(0)@binding(1)var<storage>cW:array<eC>;@group(0)@binding(2)var<storage>bM:array<c9>;@group(0)@binding(3)var<storage>aP:array<a3>;@group(0)@binding(4)var<storage>ib:array<fx>;@group(0)@binding(5)var<storage,read_write>b2:array<aQ>;@group(0)@binding(6)var<storage,read_write>ia:array<L>;const o=256u;var<workgroup>aO:array<a3,510>;var<workgroup>gq:array<j,o>;var<workgroup>dF:array<L,o>;var<workgroup>ej:array<L,o>;var<workgroup>ei:array<m,o>;fn ie(al:ptr<function,a3>,h9:j)->m{var p=h9;var bC=e;while bC<firstTrailingBit(o){let am=2u*o-(2u<<(firstTrailingBit(o)-bC));if((p>>bC)&f)!=e{let dG=dT(aO[am+(p>>bC)-f],*al);if dG.b>e{break;}*al=dG;p-=f<<bC;}bC+=f;}if p>e{while bC>e{bC-=f;let am=2u*o-(2u<<(firstTrailingBit(o)-bC));let dG=dT(aO[am+(p>>bC)- f],*al);if dG.b==e{*al=dG;p-=f<<bC;}}}if p>e{return m(p)- 1;}else{return m(~e-(*al).a);}}fn ic(p:j)->m{if p<n.eA{return cW[p].ac;}else{return-2147483648;}}@compute @workgroup_size(256)fn main(@builtin(global_invocation_id)N:M,@builtin(local_invocation_id)k:M,@builtin(workgroup_id)aq:M){var al:a3;if k.x<aq.x{al=aP[k.x];}aO[k.x]=al;for(var i=e;i<firstTrailingBit(o);i+=f){workgroupBarrier();if k.x+(f<<i)<o{let av=aO[k.x+(f<<i)];al=dT(al,av);}workgroupBarrier();aO[k.x]=al;}workgroupBarrier();let fh=aO[0].b;let fg=o- f-k.x;var p=e;for(var i=e;i<firstTrailingBit(o);i+=f){let bE=p+((o/2u)>>i);if fg<aO[bE].b{p=bE;}}let b=aO[p].b;var l=vec4(-1e9,-1e9,1e9,1e9);if fg<b{let gw=ib[p*o+b-fg- f];gq[k.x]=gw.dS;l=gw.l;}for(var i=e;i<firstTrailingBit(o);i+=f){dF[k.x]=l;workgroupBarrier();if k.x>=(f<<i){l=dU(dF[k.x-(f<<i)],l);}workgroupBarrier();}dF[k.x]=l;let cX=ic(N.x);let cd=cX>=0;al=a3(f-j(cd),j(cd));aO[k.x]=al;if cd{let aU=bM[cX];l=vec4(h(aU.J),h(aU.S),h(aU.T),h(aU.V));}else{l=vec4(-1e9,-1e9,1e9,1e9);}var gs=e;for(var i=e;i<firstTrailingBit(o)- f;i+=f){let gv=2u*o-(f<<(firstTrailingBit(o)-i));workgroupBarrier();if k.x<f<<(firstTrailingBit(o)- f-i){let gu=gs+k.x*2u;aO[gv+k.x]=dT(aO[gu],aO[gu+f]);}gs=gv;}workgroupBarrier();al=a3();var aT=ie(&al,k.x);ei[k.x]=aT;workgroupBarrier();let ek=select(aT- 1,ei[aT],aT>=0);var dE:m;if aT>=0{dE=m(aq.x*o)+aT;}else if aT+m(fh)>=0{dE=m(gq[m(o)+aT]);}else{dE=-1;}for(var i=e;i<firstTrailingBit(o);i+=f){if i!=e{ei[k.x]=aT;}ej[k.x]=l;workgroupBarrier();if aT>=0{l=dU(ej[aT],l);aT=ei[aT];}workgroupBarrier();}if aT+m(fh)>=0{l=dU(dF[m(o)+aT],l);}ej[k.x]=l;workgroupBarrier();if!cd&&N.x<n.eA{let gt=cW[dE];let ac=gt.ac;let dS=gt.p;let p=~cX;b2[p].ac=j(ac);b2[p].bH=b2[dS].bH;if ek>=0{l=ej[ek];}else if ek+m(fh)>=0{l=dF[m(o)+ek];}else{l=vec4(-1e9,-1e9,1e9,1e9);}}if N.x<n.eA{ia[N.x]=l;}}`
