/* eslint-disable */
import drawtag from './shared/drawtag.js';
import clip from './shared/clip.js';
import bbox from './shared/bbox.js';
import config from './shared/config.js';
import pre from './shared/pre.js';

export default `${pre}${config}
${bbox}
${clip}
${drawtag}
@group(0)@binding(0)var<uniform>n:aR;@group(0)@binding(1)var<storage>cW:array<eB>;@group(0)@binding(2)var<storage>bL:array<c8>;@group(0)@binding(3)var<storage>aN:array<a3>;@group(0)@binding(4)var<storage>ic:array<fw>;@group(0)@binding(5)var<storage,read_write>b_:array<aQ>;@group(0)@binding(6)var<storage,read_write>ib:array<L>;const o=256u;var<workgroup>aM:array<a3,510>;var<workgroup>gq:array<j,o>;var<workgroup>dD:array<L,o>;var<workgroup>eh:array<L,o>;var<workgroup>eg:array<m,o>;fn ig(al:ptr<function,a3>,ia:j)->m{var p=ia;var bC=e;while bC<firstTrailingBit(o){let aO=2u*o-(2u<<(firstTrailingBit(o)-bC));if((p>>bC)&f)!=e{let dE=dR(aM[aO+(p>>bC)-f],*al);if dE.b>e{break;}*al=dE;p-=f<<bC;}bC+=f;}if p>e{while bC>e{bC-=f;let aO=2u*o-(2u<<(firstTrailingBit(o)-bC));let dE=dR(aM[aO+(p>>bC)- f],*al);if dE.b==e{*al=dE;p-=f<<bC;}}}if p>e{return m(p)- 1;}else{return m(~e-(*al).a);}}fn ie(p:j)->m{if p<n.ez{return cW[p].ac;}else{return-2147483648;}}@compute @workgroup_size(256)fn main(@builtin(global_invocation_id)N:M,@builtin(local_invocation_id)k:M,@builtin(workgroup_id)ap:M){var al:a3;if k.x<ap.x{al=aN[k.x];}aM[k.x]=al;for(var i=e;i<firstTrailingBit(o);i+=f){workgroupBarrier();if k.x+(f<<i)<o{let au=aM[k.x+(f<<i)];al=dR(al,au);}workgroupBarrier();aM[k.x]=al;}workgroupBarrier();let ff=aM[0].b;let fe=o- f-k.x;var p=e;for(var i=e;i<firstTrailingBit(o);i+=f){let bE=p+((o/2u)>>i);if fe<aM[bE].b{p=bE;}}let b=aM[p].b;var l=vec4(-1e9,-1e9,1e9,1e9);if fe<b{let gw=ic[p*o+b-fe- f];gq[k.x]=gw.dQ;l=gw.l;}for(var i=e;i<firstTrailingBit(o);i+=f){dD[k.x]=l;workgroupBarrier();if k.x>=(f<<i){l=dS(dD[k.x-(f<<i)],l);}workgroupBarrier();}dD[k.x]=l;let cX=ie(N.x);let cc=cX>=0;al=a3(f-j(cc),j(cc));aM[k.x]=al;if cc{let aU=bL[cX];l=vec4(h(aU.J),h(aU.S),h(aU.T),h(aU.V));}else{l=vec4(-1e9,-1e9,1e9,1e9);}var gs=e;for(var i=e;i<firstTrailingBit(o)- f;i+=f){let gv=2u*o-(f<<(firstTrailingBit(o)-i));workgroupBarrier();if k.x<f<<(firstTrailingBit(o)- f-i){let gu=gs+k.x*2u;aM[gv+k.x]=dR(aM[gu],aM[gu+f]);}gs=gv;}workgroupBarrier();al=a3();var aT=ig(&al,k.x);eg[k.x]=aT;workgroupBarrier();let ei=select(aT- 1,eg[aT],aT>=0);var dC:m;if aT>=0{dC=m(ap.x*o)+aT;}else if aT+m(ff)>=0{dC=m(gq[m(o)+aT]);}else{dC=-1;}for(var i=e;i<firstTrailingBit(o);i+=f){if i!=e{eg[k.x]=aT;}eh[k.x]=l;workgroupBarrier();if aT>=0{l=dS(eh[aT],l);aT=eg[aT];}workgroupBarrier();}if aT+m(ff)>=0{l=dS(dD[m(o)+aT],l);}eh[k.x]=l;workgroupBarrier();if!cc&&N.x<n.ez{let gt=cW[dC];let ac=gt.ac;let dQ=gt.p;let p=~cX;b_[p].ac=j(ac);b_[p].bG=b_[dQ].bG;if ei>=0{l=eh[ei];}else if ei+m(ff)>=0{l=dD[m(o)+ei];}else{l=vec4(-1e9,-1e9,1e9,1e9);}}if N.x<n.ez{ib[N.x]=l;}}`
