/* eslint-disable */
import util from './shared/util.js';
import transform from './shared/transform.js';
import bbox from './shared/bbox.js';
import drawtag from './shared/drawtag.js';
import clip from './shared/clip.js';
import config from './shared/config.js';
import pre from './shared/pre.js';

export default `${pre}${config}
${clip}
${drawtag}
${bbox}
${transform}
@group(0)@binding(0)var<uniform>n:aR;@group(0)@binding(1)var<storage>u:aX;@group(0)@binding(2)var<storage>aN:array<aQ>;@group(0)@binding(3)var<storage>aU:array<c8>;@group(0)@binding(4)var<storage,read_write>dH:array<aQ>;@group(0)@binding(5)var<storage,read_write>info:aX;@group(0)@binding(6)var<storage,read_write>cW:array<eB>;${util}
const o=256u;var<workgroup>aF:array<aQ,o>;@compute @workgroup_size(256)fn main(@builtin(global_invocation_id)N:M,@builtin(local_invocation_id)k:M,@builtin(workgroup_id)ap:M){let p=N.x;var agg=iv();if k.x<ap.x{agg=aN[k.x];}aF[k.x]=agg;for(var i=e;i<firstTrailingBit(o);i+=f){workgroupBarrier();if k.x+(f<<i)<o{let au=aF[k.x+(f<<i)];agg=ex(agg,au);}workgroupBarrier();aF[k.x]=agg;}workgroupBarrier();var bu=aF[0];workgroupBarrier();let K=gG(p);agg=g3(K);aF[k.x]=agg;for(var i=e;i<firstTrailingBit(o);i+=f){workgroupBarrier();if k.x>=f<<i{let au=aF[k.x-(f<<i)];agg=ex(agg,au);}workgroupBarrier();aF[k.x]=agg;}workgroupBarrier();if k.x>e{bu=ex(bu,aF[k.x-f]);}if p<n.cN{dH[p]=bu;}let E=n.fu+bu.bF;let Z=bu.R;if K==fs||K==ew||K==ev||K==eu||K==dO{let l=aU[bu.ac];let ji=j(l.ad>=c);var Y=aP();var ad=l.ad;if ad>=c||K==ew||K==ev||K==eu{Y=gH(n.ey,l.bH);}if ad>=c{let P=Y.P;ad*=sqrt(abs(P.x*P.w-P.y*P.z));}switch K{case fs:{info[Z]=bitcast<j>(ad);}case ew:{info[Z]=bitcast<j>(ad);var s=bitcast<B>(vec2(u[E+f],u[E+2u]));var v=bitcast<B>(vec2(u[E+3u],u[E+4u]));s=c0(Y,s);v=c0(Y,v);let e6=v-s;let bd=d/dot(e6,e6);let e5=e6*bd;let dK=-dot(s,e5);info[Z+f]=bitcast<j>(e5.x);info[Z+2u]=bitcast<j>(e5.y);info[Z+3u]=bitcast<j>(dK);}case ev:{let e4=d/h(1<<12u);info[Z]=bitcast<j>(ad);var s=bitcast<B>(vec2(u[E+f],u[E+2u]));var v=bitcast<B>(vec2(u[E+3u],u[E+4u]));var bA=bitcast<h>(u[E+5u]);var bc=bitcast<h>(u[E+6u]);let f6=fk(Y);var d_=aP();var a8=c;var aV=c;var bE=e;var aE=e;if abs(bA-bc)<=e4{bE=g9;let f5=bA/distance(s,v);d_=dI(f8(s,v),f6);aV=f5*f5;}else{bE=iE;if all(s==v){bE=ha;s+=e4;}if bc==c{aE|=g7;let hU=s;s=v;v=hU;let hT=bA;bA=bc;bc=hT;}a8=bA/(bA-bc);let f4=(d-a8)*s+a8*v;aV=bc/(distance(f4,v));let e3=dI(f8(f4,v),f6);var e2=e3;if abs(aV-d)<=e4{bE=g8;let bd=.5*abs(d-a8);e2=dI(aP(vec4(bd,c,0.,bd),vec2(c)),e3);}else{let a=aV*aV- d;let f3=abs(d-a8)/a;let hS=aV*f3;let hR=sqrt(abs(a))*f3;e2=dI(aP(vec4(hS,c,0.,hR),vec2(c)),e3);}d_=e2;}let d2=bitcast<cn>(d_.P);let f2=bitcast<vec2u>(d_.b0);info[Z+f]=d2.x;info[Z+2u]=d2.y;info[Z+3u]=d2.z;info[Z+4u]=d2.w;info[Z+5u]=f2.x;info[Z+6u]=f2.y;info[Z+7u]=bitcast<j>(a8);info[Z+8u]=bitcast<j>(aV);info[Z+9u]=bitcast<j>((aE<<3u)|bE);}case eu:{info[Z]=bitcast<j>(ad);let d1=fk(Y);let d0=bitcast<cn>(d1.P);let f1=bitcast<vec2u>(d1.b0);info[Z+f]=d0.x;info[Z+2u]=d0.y;info[Z+3u]=d0.z;info[Z+4u]=d0.w;info[Z+5u]=f1.x;info[Z+6u]=f1.y;info[Z+7u]=u[E];info[Z+8u]=u[E+f];}default:{}}}if K==dO||K==et{var ac=~p;if K==dO{ac=bu.ac;}cW[bu.cl]=eB(p,m(ac));}}fn f8(s:B,v:B)->aP{let hQ=f7(s,v);let d1=fk(hQ);let hP=f7(vec2(c),vec2(d,c));return dI(hP,d1);}fn f7(s:B,v:B)->aP{return aP(vec4(v.y-s.y,s.x-v.x,v.x-s.x,v.y-s.y),vec2(s.x,s.y));}`
