/* eslint-disable */
import util from './shared/util.js';
import transform from './shared/transform.js';
import bbox from './shared/bbox.js';
import drawtag from './shared/drawtag.js';
import clip from './shared/clip.js';
import config from './shared/config.js';
import pre from './shared/pre.js';

export default `${pre}${config}
${clip}
${drawtag}
${bbox}
${transform}
@group(0)@binding(0)var<uniform>n:aR;@group(0)@binding(1)var<storage>s:aX;@group(0)@binding(2)var<storage>aP:array<aQ>;@group(0)@binding(3)var<storage>aU:array<c9>;@group(0)@binding(4)var<storage,read_write>dJ:array<aQ>;@group(0)@binding(5)var<storage,read_write>info:aX;@group(0)@binding(6)var<storage,read_write>cW:array<eC>;${util}
const o=256u;fn e8(c5:j,p:j)->aL{let am=c5+p*6u;let O=bitcast<L>(vec4(s[am],s[am+f],s[am+2u],s[am+3u]));let bF=bitcast<v>(vec2(s[am+4u],s[am+5u]));return aL(O,bF);}var<workgroup>aG:array<aQ,o>;@compute @workgroup_size(256)fn main(@builtin(global_invocation_id)N:M,@builtin(local_invocation_id)k:M,@builtin(workgroup_id)aq:M){let p=N.x;var agg=iv();if k.x<aq.x{agg=aP[k.x];}aG[k.x]=agg;for(var i=e;i<firstTrailingBit(o);i+=f){workgroupBarrier();if k.x+(f<<i)<o{let av=aG[k.x+(f<<i)];agg=ez(agg,av);}workgroupBarrier();aG[k.x]=agg;}workgroupBarrier();var bv=aG[0];workgroupBarrier();let K=gI(p);agg=g3(K);aG[k.x]=agg;for(var i=e;i<firstTrailingBit(o);i+=f){workgroupBarrier();if k.x>=f<<i{let av=aG[k.x-(f<<i)];agg=ez(agg,av);}workgroupBarrier();aG[k.x]=agg;}workgroupBarrier();if k.x>e{bv=ez(bv,aG[k.x-f]);}if p<n.cN{dJ[p]=bv;}let E=n.fw+bv.bH;let Z=bv.R;if K==fu||K==ey||K==ex||K==ew||K==dQ{let l=aU[bv.ac];let ji=j(l.ad>=c);var Y=aL();var ad=l.ad;if ad>=c||K==ey||K==ex||K==ew{Y=e8(n.c5,l.bJ);}if ad>=c{let O=Y.O;ad*=sqrt(abs(O.x*O.w-O.y*O.z));}switch K{case fu:{info[Z]=bitcast<j>(ad);}case ey:{info[Z]=bitcast<j>(ad);var t=bitcast<v>(vec2(s[E+f],s[E+2u]));var A=bitcast<v>(vec2(s[E+3u],s[E+4u]));t=c0(Y,t);A=c0(Y,A);let e7=A-t;let bd=d/dot(e7,e7);let e6=e7*bd;let dM=-dot(t,e6);info[Z+f]=bitcast<j>(e6.x);info[Z+2u]=bitcast<j>(e6.y);info[Z+3u]=bitcast<j>(dM);}case ex:{let e5=d/h(1<<12u);info[Z]=bitcast<j>(ad);var t=bitcast<v>(vec2(s[E+f],s[E+2u]));var A=bitcast<v>(vec2(s[E+3u],s[E+4u]));var bB=bitcast<h>(s[E+5u]);var bc=bitcast<h>(s[E+6u]);let f8=fm(Y);var d1=aL();var a8=c;var aV=c;var bG=e;var aF=e;if abs(bB-bc)<=e5{bG=g9;let f7=bB/distance(t,A);d1=dK(gc(t,A),f8);aV=f7*f7;}else{bG=iE;if all(t==A){bG=ha;t+=e5;}if bc==c{aF|=g7;let hU=t;t=A;A=hU;let hT=bB;bB=bc;bc=hT;}a8=bB/(bB-bc);let f6=(d-a8)*t+a8*A;aV=bc/(distance(f6,A));let e4=dK(gc(f6,A),f8);var e3=e4;if abs(aV-d)<=e5{bG=g8;let bd=.5*abs(d-a8);e3=dK(aL(vec4(bd,c,0.,bd),vec2(c)),e4);}else{let a=aV*aV- d;let f5=abs(d-a8)/a;let hS=aV*f5;let hR=sqrt(abs(a))*f5;e3=dK(aL(vec4(hS,c,0.,hR),vec2(c)),e4);}d1=e3;}let d4=bitcast<cn>(d1.O);let f4=bitcast<vec2u>(d1.bF);info[Z+f]=d4.x;info[Z+2u]=d4.y;info[Z+3u]=d4.z;info[Z+4u]=d4.w;info[Z+5u]=f4.x;info[Z+6u]=f4.y;info[Z+7u]=bitcast<j>(a8);info[Z+8u]=bitcast<j>(aV);info[Z+9u]=bitcast<j>((aF<<3u)|bG);}case ew:{info[Z]=bitcast<j>(ad);let d3=fm(Y);let d2=bitcast<cn>(d3.O);let f3=bitcast<vec2u>(d3.bF);info[Z+f]=d2.x;info[Z+2u]=d2.y;info[Z+3u]=d2.z;info[Z+4u]=d2.w;info[Z+5u]=f3.x;info[Z+6u]=f3.y;info[Z+7u]=s[E];info[Z+8u]=s[E+f];}default:{}}}if K==dQ||K==ev{var ac=~p;if K==dQ{ac=bv.ac;}cW[bv.cl]=eC(p,m(ac));}}fn gc(t:v,A:v)->aL{let hQ=f9(t,A);let d3=fm(hQ);let hP=f9(vec2(c),vec2(d,c));return dK(hP,d3);}fn f9(t:v,A:v)->aL{return aL(vec4(A.y-t.y,t.x-A.x,A.x-t.x,A.y-t.y),vec2(t.x,t.y));}`
