/* eslint-disable */
import util from './shared/util.js';
import transform from './shared/transform.js';
import bbox from './shared/bbox.js';
import drawtag from './shared/drawtag.js';
import clip from './shared/clip.js';
import config from './shared/config.js';
import pre from './shared/pre.js';

export default `${pre}${config}
${clip}
${drawtag}
${bbox}
${transform}
@group(0)@binding(0)var<uniform>n:aV;@group(0)@binding(1)var<storage>u:a0;@group(0)@binding(2)var<storage>aQ:array<aU>;@group(0)@binding(3)var<storage>aY:array<da>;@group(0)@binding(4)var<storage,read_write>dJ:array<aU>;@group(0)@binding(5)var<storage,read_write>info:a0;@group(0)@binding(6)var<storage,read_write>cY:array<eE>;${util}
const o=256u;var<workgroup>aG:array<aU,o>;@compute @workgroup_size(256)fn main(@builtin(global_invocation_id)N:M,@builtin(local_invocation_id)k:M,@builtin(workgroup_id)ap:M){let p=N.x;var agg=iy();if k.x<ap.x{agg=aQ[k.x];}aG[k.x]=agg;for(var i=e;i<firstTrailingBit(o);i+=f){workgroupBarrier();if k.x+(f<<i)<o{let au=aG[k.x+(f<<i)];agg=eA(agg,au);}workgroupBarrier();aG[k.x]=agg;}workgroupBarrier();var bx=aG[0];workgroupBarrier();let K=gO(p);agg=hb(K);aG[k.x]=agg;for(var i=e;i<firstTrailingBit(o);i+=f){workgroupBarrier();if k.x>=f<<i{let au=aG[k.x-(f<<i)];agg=eA(agg,au);}workgroupBarrier();aG[k.x]=agg;}workgroupBarrier();if k.x>e{bx=eA(bx,aG[k.x-f]);}if p<n.cP{dJ[p]=bx;}let E=n.fA+bx.bJ;let Y=bx.Q;if K==fy||K==ez||K==ey||K==ex||K==dQ{let l=aY[bx.ac];let jm=j(l.ad>=c);var Z=aT();var ad=l.ad;if ad>=c||K==ez||K==ey||K==ex{Z=gP(n.eB,l.bL);}if ad>=c{let P=Z.P;ad*=sqrt(abs(P.x*P.w-P.y*P.z));}switch K{case fy:{info[Y]=bitcast<j>(ad);}case ez:{info[Y]=bitcast<j>(ad);var s=bitcast<B>(vec2(u[E+f],u[E+2u]));var v=bitcast<B>(vec2(u[E+3u],u[E+4u]));s=c2(Z,s);v=c2(Z,v);let fc=v-s;let bi=d/dot(fc,fc);let fb=fc*bi;let dM=-dot(s,fb);info[Y+f]=bitcast<j>(fb.x);info[Y+2u]=bitcast<j>(fb.y);info[Y+3u]=bitcast<j>(dM);}case ey:{let fa=d/h(1<<12u);info[Y]=bitcast<j>(ad);var s=bitcast<B>(vec2(u[E+f],u[E+2u]));var v=bitcast<B>(vec2(u[E+3u],u[E+4u]));var bE=bitcast<h>(u[E+5u]);var bh=bitcast<h>(u[E+6u]);let gh=fr(Z);var d2=aT();var bd=c;var aZ=c;var bI=e;var aE=e;if abs(bE-bh)<=fa{bI=hh;let gf=bE/distance(s,v);d2=dK(gj(s,v),gh);aZ=gf*gf;}else{bI=iI;if all(s==v){bI=hi;s+=fa;}if bh==c{aE|=hf;let hY=s;s=v;v=hY;let hX=bE;bE=bh;bh=hX;}bd=bE/(bE-bh);let ge=(d-bd)*s+bd*v;aZ=bh/(distance(ge,v));let e9=dK(gj(ge,v),gh);var e8=e9;if abs(aZ-d)<=fa{bI=hg;let bi=.5*abs(d-bd);e8=dK(aT(vec4(bi,c,0.,bi),vec2(c)),e9);}else{let a=aZ*aZ- d;let gd=abs(d-bd)/a;let hW=aZ*gd;let hV=sqrt(abs(a))*gd;e8=dK(aT(vec4(hW,c,0.,hV),vec2(c)),e9);}d2=e8;}let d5=bitcast<co>(d2.P);let gc=bitcast<vec2u>(d2.b4);info[Y+f]=d5.x;info[Y+2u]=d5.y;info[Y+3u]=d5.z;info[Y+4u]=d5.w;info[Y+5u]=gc.x;info[Y+6u]=gc.y;info[Y+7u]=bitcast<j>(bd);info[Y+8u]=bitcast<j>(aZ);info[Y+9u]=bitcast<j>((aE<<3u)|bI);}case ex:{info[Y]=bitcast<j>(ad);let d4=fr(Z);let d3=bitcast<co>(d4.P);let f9=bitcast<vec2u>(d4.b4);info[Y+f]=d3.x;info[Y+2u]=d3.y;info[Y+3u]=d3.z;info[Y+4u]=d3.w;info[Y+5u]=f9.x;info[Y+6u]=f9.y;info[Y+7u]=u[E];info[Y+8u]=u[E+f];info[Y+9u]=u[E+2u];}default:{}}}if K==dQ||K==ew{var ac=~p;if K==dQ{ac=bx.ac;}cY[bx.cm]=eE(p,m(ac));}}fn gj(s:B,v:B)->aT{let hU=gi(s,v);let d4=fr(hU);let hT=gi(vec2(c),vec2(d,c));return dK(hT,d4);}fn gi(s:B,v:B)->aT{return aT(vec4(v.y-s.y,s.x-v.x,v.x-s.x,v.y-s.y),vec2(s.x,s.y));}`
