/* eslint-disable */
import ptcl from './shared/ptcl.js';
import blend from './shared/blend.js';
import config from './shared/config.js';
import segment from './shared/segment.js';

export default `struct _aI{_w:i32,_Q:u32}${segment}
${config}
@group(0)@binding(0)
var<uniform>_l:_aL;@group(0)@binding(1)
var<storage>_t:array<_aI>;@group(0)@binding(2)
var<storage>_Q:array<_dn>;${blend}
${ptcl}
const _fJ=512;@group(0)@binding(3)
var _bd:texture_storage_2d<rgba8unorm,write>;@group(0)@binding(4)
var<storage>_y:array<u32>;@group(0)@binding(5)
var _eD:texture_2d<f32>;@group(0)@binding(6)
var<storage>_k:array<u32>;@group(0)@binding(7)
var _dF:texture_2d<f32>;fn _ht(_C:u32)->_fd{let _a=_y[_C+1u];let _w=i32(_y[_C+2u]);return _fd(_a,_w);}fn _hs(_C:u32)->_fc{let _a=_y[_C+1u];let _cG=bitcast<f32>(_y[_C+2u]);return _fc(_a,_cG);}fn _hr(_C:u32)->_ec{let _cF=_y[_C+1u];return _ec(_cF);}fn _hq(_C:u32)->_gy{let _dd=_y[_C+1u];let _ak=_dd>>2u;let _bx=_dd&0x3u;let _K=_y[_C+2u];let _bX=bitcast<f32>(_k[_K]);let _fa=bitcast<f32>(_k[_K+1u]);let _do=bitcast<f32>(_k[_K+2u]);return _gy(_ak,_bx,_bX,_fa,_do);}fn _hp(_C:u32)->_gx{let _dd=_y[_C+1u];let _ak=_dd>>2u;let _bx=_dd&0x3u;let _K=_y[_C+2u];let m0=bitcast<f32>(_k[_K]);let m1=bitcast<f32>(_k[_K+1u]);let m2=bitcast<f32>(_k[_K+2u]);let m3=bitcast<f32>(_k[_K+3u]);let _z=vec4(m0,m1,m2,m3);let _cq=vec2(bitcast<f32>(_k[_K+4u]),bitcast<f32>(_k[_K+5u]));let _aV=bitcast<f32>(_k[_K+6u]);let _aK=bitcast<f32>(_k[_K+7u]);let _fI=_k[_K+8u];let _ad=_fI>>3u;let _aR=_fI&0x7u;return _gx(_ak,_bx,_z,_cq,_aV,_aK,_aR,_ad);}fn _ho(_C:u32)->_gw{let _K=_y[_C+1u];let m0=bitcast<f32>(_k[_K]);let m1=bitcast<f32>(_k[_K+1u]);let m2=bitcast<f32>(_k[_K+2u]);let m3=bitcast<f32>(_k[_K+3u]);let _z=vec4(m0,m1,m2,m3);let _cq=vec2(bitcast<f32>(_k[_K+4u]),bitcast<f32>(_k[_K+5u]));let xy=_k[_K+6u];let _fH=_k[_K+7u];
let x=f32(xy>>16u);let y=f32(xy&0xffffu);let _m=f32(_fH>>16u);let _az=f32(_fH&0xffffu);return _gw(_z,_cq,vec2(x,y),vec2(_m,_az));}fn _hn(_C:u32)->_eb{let _H=_y[_C+1u];let _aQ=bitcast<f32>(_y[_C+2u]);return _eb(_H,_aQ);}fn _bx(t:f32,_M:u32)->f32{let _hl=0u;let _hk=1u;let _hj=2u;switch _M{case 0u:{return clamp(t,0.0,1.0);}case 1u:{return fract(t);}default:{return abs(t-2.0*round(0.5*t));}}}const _V=4u;fn _fK(_a:_aI,xy:vec2<f32>,_cy:bool)->array<f32,_V>{var _ar:array<f32,_V>;let _hi=f32(_a._w);for(var i=0u;i<_V;i+=1u){_ar[i]=_hi;}var _cj=_a._Q;while _cj !=0u{let _s=_Q[_cj];let y=_s._cp.y-xy.y;let y0=clamp(y,0.0,1.0);let y1=clamp(y+_s._aq.y,0.0,1.0);let dy=y0-y1;if dy !=0.0{let _fG=1.0/_s._aq.y;let t0=(y0-y)*_fG;let t1=(y1-y)*_fG;let _fF=_s._cp.x-xy.x;let x0=_fF+t0*_s._aq.x;let x1=_fF+t1*_s._aq.x;let _hh=min(x0,x1);let _hg=max(x0,x1);for(var i=0u;i<_V;i+=1u){let _fE=f32(i);let _bK=min(_hh-_fE,1.0)-1.0e-6;let _dJ=_hg-_fE;let b=min(_dJ,1.0);let c=max(b,0.0);let d=max(_bK,0.0);let a=(b+0.5*(d*d-c*c)-_bK)/(_dJ-_bK);_ar[i]+=a*dy;}}let _aU=sign(_s._aq.x)*clamp(xy.y-_s._aU+1.0,0.0,1.0);for(var i=0u;i<_V;i+=1u){_ar[i]+=_aU;}_cj=_s._aT;}if _cy{for(var i=0u;i<_V;i+=1u){let a=_ar[i];_ar[i]=abs(a-2.0*round(0.5*a));}}else{for(var i=0u;i<_V;i+=1u){_ar[i]=min(abs(_ar[i]),1.0);}}return _ar;}fn _hm(seg:u32,_cG:f32,xy:vec2<f32>)->array<f32,_V>{var df:array<f32,_V>;for(var i=0u;i<_V;i+=1u){df[i]=1e9;}var _cj=seg;while _cj !=0u{let _s=_Q[_cj];let _aq=_s._aq;let _fD=xy+vec2(0.5,0.5)-_s._cp;let _G=1.0/dot(_aq,_aq);for(var i=0u;i<_V;i+=1u){let _dc=vec2(_fD.x+f32(i),_fD.y);let t=clamp(dot(_dc,_aq)*_G,0.0,1.0);
df[i]=min(df[i],length(_aq*t-_dc));}_cj=_s._aT;}for(var i=0u;i<_V;i+=1u){df[i]=clamp(_cG+0.5-df[i],0.0,1.0);}return df;}@compute @workgroup_size(4,16)
fn main(
@builtin(global_invocation_id)_E:vec3<u32>,@builtin(local_invocation_id)_e:vec3<u32>,@builtin(workgroup_id)_ah:vec3<u32>,){let _ap=_ah.y*_l._aB+_ah.x;let xy=vec2(f32(_E.x*_V),f32(_E.y));var rgba:array<vec4<f32>,_V>;for(var i=0u;i<_V;i+=1u){rgba[i]=unpack4x8unorm(_l._im).wzyx;}var _fy:array<array<u32,_V>,_ej>;var _aY=0u;var _ar:array<f32,_V>;var _C=_ap*_ea;let _fU=_y[_C];_C+=1u;
while true{let _f=_y[_C];if _f==_dp{break;}switch _f{case 1u:{let _aZ=_ht(_C);let _Q=_aZ._a>>1u;let _cy=(_aZ._a&1u)!=0u;let _a=_aI(_aZ._w,_Q);_ar=_fK(_a,xy,_cy);_C+=3u;}case 2u:{let _al=_hs(_C);_ar=_hm(_al._a,_al._cG,xy);_C+=3u;}case 3u:{for(var i=0u;i<_V;i+=1u){_ar[i]=1.0;}_C+=1u;}case 5u:{let _O=_hr(_C);let fg=unpack4x8unorm(_O._cF).wzyx;for(var i=0u;i<_V;i+=1u){let _bl=fg*_ar[i];rgba[i]=rgba[i]*(1.0-_bl.a)+_bl;}_C+=2u;}case 6u:{let _h=_hq(_C);let d=_h._bX*xy.x+_h._fa*xy.y+_h._do;for(var i=0u;i<_V;i+=1u){let _hf=d+_h._bX*f32(i);let x=i32(round(_bx(_hf,_h._bx)*f32(_fJ-1)));let _db=textureLoad(_eD,vec2(x,i32(_h._ak)),0);let _bl=_db*_ar[i];rgba[i]=rgba[i]*(1.0-_bl.a)+_bl;}_C+=3u;}case 7u:{let _v=_hp(_C);let _aV=_v._aV;let _aK=_v._aK;let _he=_v._aR==_gL;let _hd=_v._aR==_gM;let _hc=_v._aR==_gK;let _fC=(_v._ad&_gJ)!=0u;let _fB=select(1.0/_aK,0.0,_hd);let _hb=select(1.0,-1.0,_fC||(1.0-_aV)<0.0);let _ha=sign(1.0-_aV);for(var i=0u;i<_V;i+=1u){let _da=vec2(xy.x+f32(i),xy.y);let _fA=_v._z.xy*_da.x+_v._z.zw*_da.y+_v._cq;let x=_fA.x;let y=_fA.y;let xx=x*x;let yy=y*y;var t=0.0;var _dG=true;if _he{let a=_aK-yy;t=sqrt(a)+x;_dG=a>=0.0;}else if _hc{t=(xx+yy)/x;_dG=t>=0.0&&x !=0.0;}else if _aK>1.0{t=sqrt(xx+yy)-x*_fB;}else{let a=xx-yy;t=_hb*sqrt(a)-x*_fB;_dG=a>=0.0&&t>=0.0;}if _dG{t=_bx(_aV+_ha*t,_v._bx);t=select(t,1.0-t,_fC);let x=i32(round(t*f32(_fJ-1)));let _db=textureLoad(_eD,vec2(x,i32(_v._ak)),0);let _bl=_db*_ar[i];rgba[i]=rgba[i]*(1.0-_bl.a)+_bl;}}_C+=3u;}case 8u:{let _aC=_ho(_C);let _fz=_aC._eZ+_aC._dZ;for(var i=0u;i<_V;i+=1u){let _da=vec2(xy.x+f32(i),xy.y);let _dI=_aC._z.xy*_da.x+_aC._z.zw*_da.y+_aC._cq+_aC._eZ;
if all(_dI<_fz)&&_ar[i] !=0.0{let _dH=vec4(max(floor(_dI),_aC._eZ),min(ceil(_dI),_fz));let _eF=fract(_dI);let a=_dK(textureLoad(_dF,vec2<i32>(_dH.xy),0));let b=_dK(textureLoad(_dF,vec2<i32>(_dH.xw),0));let c=_dK(textureLoad(_dF,vec2<i32>(_dH.zy),0));let d=_dK(textureLoad(_dF,vec2<i32>(_dH.zw),0));let _db=mix(mix(a,b,_eF.y),mix(c,d,_eF.y),_eF.x);let _bl=_db*_ar[i];rgba[i]=rgba[i]*(1.0-_bl.a)+_bl;}}_C+=2u;}case 9u:{if _aY<_ej{for(var i=0u;i<_V;i+=1u){_fy[_aY][i]=pack4x8unorm(rgba[i]);rgba[i]=vec4(0.0);}}else{}_aY+=1u;_C+=1u;}case 10u:{let _bJ=_hn(_C);_aY-=1u;for(var i=0u;i<_V;i+=1u){var _fx:u32;if _aY<_ej{_fx=_fy[_aY][i];}else{}let bg=unpack4x8unorm(_fx);let fg=rgba[i]*_ar[i]*_bJ._aQ;rgba[i]=_iT(bg,fg,_bJ._H);}_C+=3u;}case 11u:{_C=_y[_C+1u];}default:{}}}let _eE=vec2<u32>(xy);for(var i=0u;i<_V;i+=1u){let _ck=_eE+vec2(i,0u);if _ck.x<_l._gI&&_ck.y<_l._gH{let fg=rgba[i];
let _bI=1.0/max(fg.a,1e-6);let _gZ=vec4(fg.rgb*_bI,fg.a);textureStore(_bd,vec2<i32>(_ck),_gZ);}}}fn _dK(rgba:vec4<f32>)->vec4<f32>{return vec4(rgba.rgb*rgba.a,rgba.a);}`
