/* eslint-disable */
import transform from './shared/transform.js';
import cubic from './shared/cubic.js';
import pathtag from './shared/pathtag.js';
import config from './shared/config.js';

export default `${config}
${pathtag}
${cubic}
${transform}
@group(0)@binding(0)var<uniform>f:aF;@group(0)@binding(1)var<storage>k:array<u32>;@group(0)@binding(2)var<storage>bV:array<X>;struct hb{B:atomic<i32>,I:atomic<i32>,J:atomic<i32>,M:atomic<i32>,S:f32,bA:u32}@group(0)@binding(3)var<storage,read_write>bD:array<hb>;@group(0)@binding(4)var<storage,read_write>el:array<fh>;var<private>bh:u32;fn bR(i:u32)->vec2f{let x=bitcast<f32>(k[bh+i]);let y=bitcast<f32>(k[bh+i+1u]);return vec2(x,y);}fn bQ(i:u32)->vec2f{let df=k[bh+i];let x=f32(i32(df<<16u)>>16u);let y=f32(i32(df)>>16u);return vec2(x,y);}fn eW(cU:u32,i:u32)->az{let Z=cU+i*6u;let eV=bitcast<f32>(k[Z]);let eU=bitcast<f32>(k[Z+1u]);let eT=bitcast<f32>(k[Z+2u]);let eS=bitcast<f32>(k[Z+3u]);let eR=bitcast<f32>(k[Z+4u]);let eQ=bitcast<f32>(k[Z+5u]);let C=vec4(eV,eU,eT,eS);let a0=vec2(eR,eQ);return az(C,a0);}fn fz(x:f32)->i32{return i32(floor(x));}fn fy(x:f32)->i32{return i32(ceil(x));}@compute @workgroup_size(256)fn main(@builtin(global_invocation_id)E:vec3u,@builtin(local_invocation_id)d:vec3u,){let i=E.x;let D=k[f.dD+(i>>2u)];bh=f.bh;let bX=(i&3u)*8u;var K=d7(D&((1u<<bX)- 1u));K=bH(bV[i>>2u],K);var bW=(D>>bX)&0xffu;let bB=&bD[K.R];let S=bitcast<f32>(k[f.im+K.dz]);if(bW&gL)!=0u{(*bB).S=S;(*bB).bA=K.bA;}let aG=bW&ff;if aG!=0u{var l:vec2f;var n:vec2f;var v:vec2f;var G:vec2f;if(bW&gM)!=0u{l=bR(K.aw);n=bR(K.aw+2u);if aG>=cT{v=bR(K.aw+4u);if aG==dB{G=bR(K.aw+6u);}}}else{l=bQ(K.aw);n=bQ(K.aw+1u);if aG>=cT{v=bQ(K.aw+2u);if aG==dB{G=bQ(K.aw+3u);}}}let P=eW(f.cU,K.bA);l=cP(P,l);n=cP(P,n);var e=vec4(min(l,n),max(l,n));if aG==gN{G=n;v=mix(G,l,1./3.);n=mix(l,G,1./3.);}else if aG>=cT{v=cP(P,v);e=vec4(min(e.xy,v),max(e.zw,v));if aG==dB{G=cP(P,G);e=vec4(min(e.xy,G),max(e.zw,G));}else{G=v;v=mix(n,v,1./3.);n=mix(n,l,1./3.);}}var aO=vec2(0.,0.);if S>=0.{aO=.5*S*vec2(length(P.C.xz),length(P.C.yw));e+=vec4(-aO,aO);}let at=u32(S>=0.);el[E.x]=fh(l,n,v,G,aO,K.R,at);if e.z>e.x||e.w>e.y{atomicMin(&(*bB).B,fz(e.x));atomicMin(&(*bB).I,fz(e.y));atomicMax(&(*bB).J,fy(e.z));atomicMax(&(*bB).M,fy(e.w));}}}`
