/* eslint-disable */
import transform from './shared/transform.js';
import cubic from './shared/cubic.js';
import pathtag from './shared/pathtag.js';
import config from './shared/config.js';

export default `${config}
${pathtag}
${cubic}
${transform}
@group(0)@binding(0)var<uniform>_m:_aG;@group(0)@binding(1)var<storage>_n:array<u32>;@group(0)@binding(2)var<storage>_bV:array<_ad>;struct _hg{x0:atomic<i32>,y0:atomic<i32>,x1:atomic<i32>,y1:atomic<i32>,_L:f32,_bz:u32}@group(0)@binding(3)var<storage,read_write>_bD:array<_hg>;@group(0)@binding(4)var<storage,read_write>_cD:array<_fm>;var<private>_bj:u32;fn _bO(ix:u32)->vec2<f32>{let x=bitcast<f32>(_n[_bj+ix]);let y=bitcast<f32>(_n[_bj+ix+1u]);return vec2(x,y);}fn _bN(ix:u32)->vec2<f32>{let _g=_n[_bj+ix];let x=f32(i32(_g<<16u)>>16u);let y=f32(i32(_g)>>16u);return vec2(x,y);}fn _eS(_cR:u32,ix:u32)->_az{let _t=_cR+ix*6u;let c0=bitcast<f32>(_n[_t]);let c1=bitcast<f32>(_n[_t+1u]);let c2=bitcast<f32>(_n[_t+2u]);let c3=bitcast<f32>(_n[_t+3u]);let c4=bitcast<f32>(_n[_t+4u]);let c5=bitcast<f32>(_n[_t+5u]);let _i=vec4(c0,c1,c2,c3);let _bc=vec2(c4,c5);return _az(_i,_bc);}fn _fB(x:f32)->i32{return i32(floor(x));}fn _fA(x:f32)->i32{return i32(ceil(x));}@compute @workgroup_size(256)fn main(@builtin(global_invocation_id)_G:vec3<u32>,@builtin(local_invocation_id)_f:vec3<u32>,){let ix=_G.x;let _D=_n[_m._dE+(ix>>2u)];_bj=_m._bj;let _bX=(ix&3u)*8u;var tm=_el(_D&((1u<<_bX)- 1u));tm=_bF(_bV[ix>>2u],tm);var _bW=(_D>>_bX)&0xffu;let _C=&_bD[tm._P];let _L=bitcast<f32>(_n[_m._ir+tm._dA]);if(_bW&_gJ)!=0u{(*_C)._L=_L;(*_C)._bz=tm._bz;}let _aH=_bW&_fk;if _aH!=0u{var p0:vec2<f32>;var p1:vec2<f32>;var p2:vec2<f32>;var p3:vec2<f32>;if(_bW&_gK)!=0u{p0=_bO(tm._av);p1=_bO(tm._av+2u);if _aH>=_cQ{p2=_bO(tm._av+4u);if _aH==_dC{p3=_bO(tm._av+6u);}}}else{p0=_bN(tm._av);p1=_bN(tm._av+1u);if _aH>=_cQ{p2=_bN(tm._av+2u);if _aH==_dC{p3=_bN(tm._av+3u);}}}let _x=_eS(_m._cR,tm._bz);p0=_cM(_x,p0);p1=_cM(_x,p1);var _b=vec4(min(p0,p1),max(p0,p1));if _aH==_gL{p3=p1;p2=mix(p3,p0,1./3.);p1=mix(p0,p3,1./3.);}else if _aH>=_cQ{p2=_cM(_x,p2);_b=vec4(min(_b.xy,p2),max(_b.zw,p2));if _aH==_dC{p3=_cM(_x,p3);_b=vec4(min(_b.xy,p3),max(_b.zw,p3));}else{p3=p2;p2=mix(p1,p2,1./3.);p1=mix(p1,p0,1./3.);}}var _an=vec2(0.,0.);if _L>=0.{_an=.5*_L*vec2(length(_x._i.xz),length(_x._i.yw));_b+=vec4(-_an,_an);}let _ae=u32(_L>=0.);_cD[_G.x]=_fm(p0,p1,p2,p3,_an,tm._P,_ae);if _b.z>_b.x||_b.w>_b.y{atomicMin(&(*_C).x0,_fB(_b.x));atomicMin(&(*_C).y0,_fB(_b.y));atomicMax(&(*_C).x1,_fA(_b.z));atomicMax(&(*_C).y1,_fA(_b.w));}}}`
